import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Ibarra_Real_Nova,
  Public_Sans,
} from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const IbarraNova = Ibarra_Real_Nova({
  variable: "--font-ibarra-nova",
  subsets: ["latin"],
});

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Daniel Okafor | Portfolio",
  openGraph: {
    title: "Daniel Okafor | Portfolio",
    description: "Portfolio of Daniel Okafor, a software developer.",
    url: "https://my-website-l7bx.vercel.app/",
    siteName: "Daniel Okafor",
    images: [
      {
        url: "https://my-website-l7bx.vercel.app/_next/image?url=%2Fimages%2Fhomepage%2Fdesktop%2FBuchi-tablet.jpeg&w=828&q=75",
        width: 1200,
        height: 630,
        alt: "Daniel Okafor Portfolio",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Daniel Okafor | Portfolio",
    description: "Portfolio of Daniel Okafor, a software developer.",
    images: [
      "https://my-website-l7bx.vercel.app/_next/image?url=%2Fimages%2Fhomepage%2Fdesktop%2FBuchi-tablet.jpeg&w=828&q=75",
    ],
    creator: "@bucheed",
  },
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
    shortcut: "/favicon-32x32.png",
  },
  keywords: [
    "Daniel Okafor",
    "Portfolio",
    "Software Developer",
    "Web Developer",
    "Full Stack Developer",
    "Next.js",
    "React",
    "JavaScript",
    "TypeScript",
    "Node.js",
    "Express",
    "MongoDB",
    "PostgreSQL",
    "CSS",
    "HTML",
    "Frontend Developer",
    "Backend Developer",
    "UI/UX Designer",
    "Open Source",
    "Open Source Contributor",
    "Web Design",
    "Web Development",
    "Software Engineering",
    "Programming",
    "Coding",
    "Tech",
    "Technology",
    "Developer Portfolio",
    "Personal Website",
    "Developer Blog",
    "Developer Resume",
    "Developer CV",
    "Developer Projects",
    "Developer Skills",
    "Developer Experience",
    "Developer Tools",
    "Developer Community",
    "Developer Resources",
    "Developer Tutorials",
    "Developer Articles",
    "Developer News",
    "Developer Tips",
    "Developer Tricks",
    "Developer Guides",
    "Developer Documentation",
    "Developer Interviews",
  ],
  authors: [
    {
      name: "Daniel Okafor",
      url: "https://danielokafor.dev",
    },
  ],
  creator: "Daniel Okafor",
  publisher: "Daniel Okafor",
  themeColor: "#000000",
  robots: {
    index: true,
    follow: true,
    nocache: false,
    noimageindex: false,
    noarchive: false,
    nosnippet: false,
  },
  applicationName: "Daniel Okafor Portfolio",
  formatDetection: {
    telephone: false,
    address: false,
    email: false,
  },
  viewport: "width=device-width, initial-scale=1",
  referrer: "no-referrer-when-downgrade",
  colorScheme: "dark light",

  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${IbarraNova.variable} ${publicSans.variable} antialiased`}
      >
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
